const MESSAGES = {
  validationFailed: 'Input fields validation failed',
  invalidLoginOrPassword: 'Invalid email or password',
  userSigninSuccess: 'User signed in successfully',
  userAlreadyExist: 'User  already exists with entered credentials',
  roleIdDoesntExist: 'Role with the given id does not exist',
  cityIdDoesntExist: 'City with the given id does not exist',
  stateCodeDoesntExist: 'State with the given code does not exist',
  countryCodeDoesntExist: 'Country with the given code does not exist',
  userCreated: 'User has been created successfully',
  userNotCreated: 'User has not been created',
  userNotFound: 'User with given id is not found',
  userDeleted: 'User had been deleted successfully with the given id',
  userUpdated: 'User has been updated successfully',
  addressNotFound: 'Address not found with the user id',
  roleNotFound: 'Role not found with the user id',
  userNotUpdated: 'User has not been updated ',
  fetchAllUsers: 'Fetch all the users',
  userNotExist: 'User does not exists',
  userDisplayed: 'User has been displayed',
  userUpdated: 'User has been updated',
  userNotDeleted: 'User is not deleted',
  locationCreated: 'Location is successfully created',
  locationUpdated: 'Location has been successfully updated',
  locationDeleted: 'Location has been deleted',
  locationNotFound: 'Location does not exists',
  locationDisplayed: 'Location has been successfully displayed',
  fetchAllLocations: 'All locations are being displayed',
  invalidFieldUpdate: 'Invalid field update',
  fetchAllUserLocation: 'Fetch all assigned users at location',
  userNotAssignedLocation: 'No users assigned to GeofenceLocation id',
  userNotAssignedLocation: 'User is not assigned this location',
  checkInNotAllowed: 'You are not allowed to check-in with current location',
  checkIn: 'User has been successfully checked-in',
  checkOut: 'User has been successfully checked-out',
  attendanceRuleUpdated: 'Attendance rule has been updated successfully',
  attendanceRuleDisplay: 'Attendance rule has been displayed successfully',
  attendanceRuleNotFound: 'Attendance rule not found',
  missingFieldData: 'Field data is missing',
  leaveReqDisplayed: 'All leave requests has been displayed',
  leaveReqCreated: 'Leave request has been created',
  attendanceDisplay: 'Attendance log has been displayed',
  faceDetectLogsDisplay: 'Face Detect log has been displayed',
};
const ATTENDANCE_STATUSES = {
  Present: 'Present',
  Absent: 'Absent',
  Late: 'Late',
  HalfDay: 'HalfDay',
  NotMarked: 'NotMarked',
};
const NOTIFICATION_STATUSES = {
  Sent: 'Sent',
  Pending: 'Pending',
};
const GENDER = {
  Female: 'Female',
  Male: 'Male',
  NotToSay: 'NotToSay',
};
const STATUS = {
  Active: 'Active',
  Inactive: 'Inactive',
};
module.exports = {
  MESSAGES,
  ATTENDANCE_STATUSES,
  NOTIFICATION_STATUSES,
  GENDER,
  STATUS,
};
